### ISSUE TITLE
Recommended configuration?

### ISSUE THREAD

**Issue by ejsmith** [Onalytica/CloudWatchLogsTarget#1]
How do you recommend using this target? I'm guessing I should put it inside of an AsyncWrapper?

**Comment by nanestev** [comment]
Hi,

There's example nlog.config file bundled in the package. Here's the example
configuration:

<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance">
  <targets>
    <target name="bw"
            xsi:type="BufferingWrapper"
            slidingTimeout="true"
            bufferSize="100"
            flushTimeout="60000">
      <target name="cwl"
              xsi:type="CloudWatchLogs"
              AWSAccessKeyId="aws-access-key-id"
              AWSSecretKey="aws-secret-key"
              AWSRegion="aws-region"
              LogGroupName="log-group"
              LogStreamName="log-stream"
              layout="${longdate} [${threadid}] ${level} ${logger} [${ndc}]
- ${message}"/>
  </target>
  </targets>
  <rules>
    <logger name="*" minLevel="Info" appendTo="bw"/>
  </rules>
  </nlog>

Example uses BufferingWrapper, but it should also work with AsyncWrapper.

Hope this helps.

**Comment by ejsmith** [comment]
Thank you!
