### ISSUE TITLE
CloudWatchLogsClientWrapper optional insert AmazonCloudWatchLogsClient

### ISSUE THREAD

**Issue by KennethWKZ** [Onalytica/CloudWatchLogsTarget#10]
Possible to constructs AmazonCloudWatchLogsClient with the credentials loaded from the application's default configuration, so it can load from the Instance Profile service on an EC2 instance instead of expose our aws access id, secret key in code?

Example:

`AmazonCloudWatchLogsClient(RegionEndpoint.GetBySystemName(AWSRegion))`

`AmazonCloudWatchLogsClient()`

instead of 

`AmazonCloudWatchLogsClient(AWSAccessKeyId, AWSSecretKey, RegionEndpoint.GetBySystemName(AWSRegion))`

So we can directly using AWSSDK credentials store or AMI for enhance code security.

**Comment by nanestev** [comment]
Yeah, been thinking to change it for a while and may be now it's a good time. Creds shouldn't be required from the config but respected if present. AmazonCloudWatchLogsClient should get either config or default creds. Will find time to change it this weekend.

**Comment by KennethWKZ** [comment]
Pull Request #12 - Try to contribute. Hope my code can help. @nanestev

**Comment by nanestev** [comment]
Thanks, but I'm already working on it and I'm very close to release.
