### ISSUE TITLE
Any plan to support .net core 1.1

### ISSUE THREAD

**Issue by ghost** [Onalytica/CloudWatchLogsTarget#2]
Hey,

I tried to import your nuget package in my .net core 1.1 project. It seems .net core is not supported yet? Any plan to support it soon?

Thx
Seb

**Comment by nanestev** [comment]
Yes, I'm planing to release a version targeting netstandard. I have started working on it few weeks ago, but never finished. Watch this space in the next week or so.

**Comment by nanestev** [comment]
New [1.1.0-beta](https://www.nuget.org/packages/NLog.Targets.CloudWatchLogs/1.1.0-beta) version was submitted which also targets netstandard1.3.
