### ISSUE TITLE
Support Nlog AsyncTargetWrapper?

### ISSUE THREAD

**Issue by KennethWKZ** [Onalytica/CloudWatchLogsTarget#9]
Ya thanks for the sample configuration.
That why i cannot send the log by AsyncTargetWrapper because just found that this only support BufferWrapper?

**Comment by nanestev** [comment]
It should work with any wrapper, but I haven't tested it. I'm using it with BufferingWrapper, because it seems to be the recommended way as per this wiki https://github.com/nlog/NLog/wiki/BufferingWrapper-target. It says:
> Using the slidingTimeout is preferred over the async attribute and AsyncWrapper.
